from __future__ import annotations

import base64
import io
import json
import os
import time
import uuid
import zipfile
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple

import pandas as pd
import requests
import streamlit as st
from dotenv import load_dotenv
from openai import OpenAI

import report_builder_v911_r3 as report_builder_module

from report_builder_v911_r3 import (
    TRANSLATION_GLOSSARY_PROMPTS,
    LANGUAGE_FILE_SUFFIXES,
    MARKET_LABELS,
    OUTPUT_LANGUAGES,
    STATUS_LABELS,
    action_for_detail,
    clean_text,
    create_bundle_zip_bytes,
    create_product_excel_bytes,
    create_product_report_bytes,
    dominant_status,
    halal_decision,
    market_decision,
    normalize_status,
    normalized_reason,
    output_file_name,
    output_zip_name,
    required_evidence_for_detail,
    safe_filename,
    safe_int,
    status_counts,
)

# Streamlit ?? ? ?? report_builder? ????? ??????
# ? ??? ImportError? ???? ??? ?? ?????.
REPORT_BUILD_ID = getattr(
    report_builder_module,
    "REPORT_BUILD_ID",
    "legacy-report-builder",
)


st.set_page_config(
    page_title="Global K-Beauty Compliance",
    page_icon="🌍",
    layout="wide",
)


# ============================================================
# 기본 설정
# ============================================================
load_dotenv()

APP_VERSION = "v9.1.1"


def get_config(name: str, default: Optional[str] = None) -> Optional[str]:
    """Read configuration from environment first, then Streamlit secrets."""
    value = os.environ.get(name)
    if value is not None and str(value).strip():
        return str(value).strip()
    try:
        secrets = getattr(st, "secrets", {})
        if name in secrets and str(secrets[name]).strip():
            return str(secrets[name]).strip()
    except Exception:
        pass
    return default


API_BASE_URL = clean_text(
    get_config("API_BASE_URL", "https://k-beauty-api.onrender.com"),
    "https://k-beauty-api.onrender.com",
).rstrip("/")
MULTI_COMPLIANCE_API_URL = (
    f"{API_BASE_URL}/api/v2/multi-compliance-report"
)
COMPLIANCE_API_URL = f"{API_BASE_URL}/api/v1/compliance-report"
DATABASE_STATUS_URL = f"{API_BASE_URL}/api/v1/database-status"

OPENAI_API_KEY = get_config("OPENAI_API_KEY")
MASTER_KEY = get_config("MASTER_KEY")
client = OpenAI(api_key=OPENAI_API_KEY) if OPENAI_API_KEY else None

REGULATORY_MARKETS = [
    "US",
    "EU",
    "UK",
    "CN",
    "ASEAN",
    "SFDA",
    "EAC",
]

MARKET_OPTIONS = {
    "US": "미국(US) — FDA / California",
    "EU": "유럽연합(EU) — Cosmetics Regulation",
    "UK": "영국(UK) — UK Cosmetics Regulation",
    "CN": "중국(CN) — NMPA",
    "ASEAN": "아세안(ASEAN) — ASEAN Cosmetic Directive",
    "SFDA": "사우디아라비아(SFDA)",
    "EAC": "유라시아경제연합(EAEU) — Eurasian Economic Union",
}

STATUS_BADGES = {
    "PASS": "통과",
    "FAIL": "부적합",
    "BANNED": "금지",
    "RESTRICTED": "제한",
    "WARNING_REQUIRED": "경고·표시 필요",
    "REGULATED": "규제 대상",
    "REVIEW_REQUIRED": "확인 필요",
    "VERIFICATION_REQUIRED": "명칭·기원 검증 필요",
}


# ============================================================
# 세션 상태
# ============================================================
def initialize_session_state() -> None:
    defaults = {
        "free_analysis_units_left": 3,
        "current_auth_msg": None,
        "current_auth_tier": "INVALID",
        "last_entered_key": None,
        "disclaimer_agreed": False,
        "analysis_result": None,
        "localized_outputs": {},
        "report_build_id": REPORT_BUILD_ID,
    }
    for key, value in defaults.items():
        if key not in st.session_state:
            st.session_state[key] = value

    # A report-builder update must never reuse Word/Excel bytes generated by
    # an older session. Keep the analysis result, but invalidate old downloads.
    if st.session_state.get("report_build_id") != REPORT_BUILD_ID:
        st.session_state.localized_outputs = {}
        st.session_state.report_build_id = REPORT_BUILD_ID


def reset_results() -> None:
    st.session_state.analysis_result = None
    st.session_state.localized_outputs = {}


# ============================================================
# 인증 및 네트워크
# ============================================================
def verify_gumroad_license(
    product_permalink: str,
    key: str,
    increment: bool = False,
) -> dict:
    response = requests.post(
        "https://api.gumroad.com/v2/licenses/verify",
        data={
            "product_permalink": product_permalink,
            "license_key": clean_text(key),
            "increment_uses_count": "true" if increment else "false",
        },
        timeout=12,
    )
    response.raise_for_status()
    payload = response.json()
    return payload if isinstance(payload, dict) else {}


def check_license_status(key: str) -> Tuple[str, str, int]:
    key = clean_text(key)
    if MASTER_KEY and key == MASTER_KEY:
        return "PRO", "CEO Master Key 활성화 — 무제한", 0

    try:
        pro = verify_gumroad_license("pkoph", key, increment=False)
        if pro.get("success") and not pro.get("purchase", {}).get("refunded"):
            return "PRO", "PRO Bulk 이용 가능 — 무제한", 0

        standard = verify_gumroad_license(
            "lyibre",
            key,
            increment=False,
        )
        if standard.get("success") and not standard.get("purchase", {}).get("refunded"):
            uses = safe_int(standard.get("uses"))
            if uses >= 50:
                return "EXPIRED", "월 분석 한도 50건을 모두 사용했습니다.", uses
            return "STANDARD", f"Standard 이용 가능 — 잔여 {50 - uses}/50건", uses
    except requests.RequestException:
        return "ERROR", "라이선스 서버 연결에 실패했습니다.", 0
    except ValueError:
        return "ERROR", "라이선스 서버 응답이 올바르지 않습니다.", 0

    return "INVALID", "유효하지 않거나 환불된 라이선스 키입니다.", 0


def consume_standard_units(key: str, units: int) -> Tuple[bool, str]:
    if units <= 0:
        return True, ""
    try:
        for _ in range(units):
            payload = verify_gumroad_license(
                "lyibre",
                key,
                increment=True,
            )
            if not payload.get("success"):
                return False, "Standard 분석 건수 반영에 실패했습니다."
            if safe_int(payload.get("uses")) > 50:
                return False, "월 분석 한도를 초과했습니다."
    except (requests.RequestException, ValueError):
        return False, "라이선스 사용 건수 반영 중 오류가 발생했습니다."
    return True, ""


@st.cache_data(show_spinner=False, ttl=300)
def fetch_database_status() -> dict:
    try:
        response = requests.get(DATABASE_STATUS_URL, timeout=10)
        response.raise_for_status()
        payload = response.json()
        return payload if isinstance(payload, dict) else {}
    except (requests.RequestException, ValueError):
        return {}


# ============================================================
# 파일 읽기 및 성분 추출
# ============================================================
@st.cache_data(show_spinner=False, ttl=3600)
def extract_ingredients_from_image(
    file_bytes: bytes,
) -> Tuple[List[str], Optional[str]]:
    if client is None:
        return [], "OPENAI_API_KEY가 설정되지 않았습니다."

    base64_image = base64.b64encode(file_bytes).decode("utf-8")
    prompt = (
        "화장품 전성분 이름을 원래 순서대로 추출하세요. "
        "성분 사이는 반드시 세로줄(|)로 구분하고 다른 설명은 쓰지 마세요. "
        "쉼표는 성분명 내부에 포함될 수 있으므로 구분자로 사용하지 마세요."
    )

    try:
        response = client.chat.completions.create(
            model="gpt-4o",
            messages=[
                {
                    "role": "user",
                    "content": [
                        {"type": "text", "text": prompt},
                        {
                            "type": "image_url",
                            "image_url": {
                                "url": (
                                    "data:image/jpeg;base64,"
                                    f"{base64_image}"
                                )
                            },
                        },
                    ],
                }
            ],
            temperature=0.0,
        )
        content = response.choices[0].message.content or ""
        values = [clean_text(value) for value in content.split("|")]
        return dedupe_preserve(values), None
    except Exception as exc:
        return [], f"이미지 성분 추출 실패: {type(exc).__name__}: {exc}"



@st.cache_data(show_spinner=False, ttl=86400)
def translate_report_texts(
    texts: Tuple[str, ...],
    language_code: str,
    protected_tokens: Tuple[str, ...] = (),
) -> Dict[str, str]:
    """보고서·Excel의 표시 문구를 한 번에 번역한다.

    규제 의미를 바꾸지 않고 토큰, INCI, CAS, 시장 코드, URL과 파일명은
    그대로 유지한다. 분석은 다시 실행하지 않으며 출력 파일만 현지화한다.
    """
    unique_texts = tuple(dedupe_preserve(texts))
    if not unique_texts:
        return {}
    if language_code not in OUTPUT_LANGUAGES:
        raise ValueError(f"지원하지 않는 출력 언어입니다: {language_code}")
    if client is None:
        raise RuntimeError(
            "다국어 파일 생성을 위한 OPENAI_API_KEY가 설정되지 않았습니다."
        )

    target_language = OUTPUT_LANGUAGES[language_code]
    result: Dict[str, str] = {}
    chunks: List[List[str]] = []
    current: List[str] = []
    current_chars = 0
    for text in unique_texts:
        if current and (len(current) >= 45 or current_chars + len(text) > 9000):
            chunks.append(current)
            current = []
            current_chars = 0
        current.append(text)
        current_chars += len(text)
    if current:
        chunks.append(current)

    for chunk in chunks:
        payload = [
            {"id": index, "source": text}
            for index, text in enumerate(chunk)
        ]
        glossary_prompt = TRANSLATION_GLOSSARY_PROMPTS.get(language_code, "")
        terminology_instruction = (
            f"\n\n{glossary_prompt}" if glossary_prompt else ""
        )
        if language_code == "en":
            style_instruction = (
                "Write clear, natural, professional regulatory English. "
                "Use short direct sentences and plain business language. "
                "Do not translate Korean word order literally. Avoid bureaucratic labels, "
                "vague phrases, and internal-system terminology. "
            )
        else:
            style_instruction = (
                "The source text is polished English. Translate it into natural, concise, "
                f"professional {target_language}. Do not translate word-for-word. "
                "Use short sentences that a business reader can understand immediately. "
                "Do not expand the text or reintroduce technical wording that was removed. "
            )
        system_prompt = (
            "You are a professional cosmetics regulatory document translator. "
            f"Translate every source string into {target_language}. "
            f"{style_instruction}"
            "Do not add legal conclusions, explanations, or unsupported claims. "
            "Preserve the exact meaning, warnings, numbering, and all placeholder tokens. "
            "Keep INCI names, CAS numbers, URLs, file names, market codes, institution "
            "acronyms, and official identifiers unchanged. Preserve question-and-answer "
            "structure where present. Return JSON only in the form "
            '{"translations":[{"id":0,"translation":"..."}]}. '
            "Placeholder tokens matching [[P####]] must remain exact."
            f"{terminology_instruction}"
        )
        try:
            response = client.chat.completions.create(
                model="gpt-4o",
                messages=[
                    {"role": "system", "content": system_prompt},
                    {
                        "role": "user",
                        "content": json.dumps(
                            {"items": payload},
                            ensure_ascii=False,
                        ),
                    },
                ],
                temperature=0.0,
            )
            content = (response.choices[0].message.content or "").strip()
            if content.startswith("```"):
                content = content.strip("`")
                if content.lower().startswith("json"):
                    content = content[4:].lstrip()
            parsed = json.loads(content)
            items = parsed.get("translations") or []
            by_id = {
                int(item["id"]): clean_text(item.get("translation"))
                for item in items
                if isinstance(item, dict) and "id" in item
            }
            for index, source in enumerate(chunk):
                translated = by_id.get(index)
                if not translated:
                    raise ValueError(f"번역 누락: {source[:80]}")
                result[source] = translated
        except Exception as exc:
            raise RuntimeError(
                f"{target_language} 출력 번역 실패: {type(exc).__name__}: {exc}"
            ) from exc
    return result


def report_translator(
    texts: Sequence[str],
    language_code: str,
    protected_tokens: Sequence[str],
) -> Dict[str, str]:
    return translate_report_texts(
        tuple(texts),
        language_code,
        tuple(protected_tokens),
    )


def dedupe_preserve(values: Sequence[str]) -> List[str]:
    result: List[str] = []
    seen: set[str] = set()
    for value in values:
        text = clean_text(value)
        key = text.casefold()
        if text and key not in seen:
            seen.add(key)
            result.append(text)
    return result


def read_uploaded_table(uploaded_file: Any) -> pd.DataFrame:
    extension = uploaded_file.name.rsplit(".", 1)[-1].casefold()
    raw_bytes = uploaded_file.getvalue()

    if extension in {"xlsx", "xls"}:
        return pd.read_excel(io.BytesIO(raw_bytes))

    encodings = ("utf-8-sig", "utf-8", "cp949", "euc-kr")
    for encoding in encodings:
        try:
            return pd.read_csv(
                io.BytesIO(raw_bytes),
                encoding=encoding,
            )
        except UnicodeDecodeError:
            continue

    return pd.read_csv(
        io.BytesIO(raw_bytes),
        encoding="utf-8",
        encoding_errors="replace",
    )


def extract_product(uploaded_file: Any) -> dict:
    source_file = uploaded_file.name
    base_name = Path(source_file).stem
    product_name = clean_text(base_name, "제품")
    extension = source_file.rsplit(".", 1)[-1].casefold()

    if extension in {"jpg", "jpeg", "png"}:
        ingredients, error = extract_ingredients_from_image(
            uploaded_file.getvalue()
        )
        return {
            "product_name": product_name,
            "source_file": source_file,
            "ingredients": ingredients,
            "preview": pd.DataFrame({"성분명": ingredients[:20]}),
            "error": error,
        }

    try:
        dataframe = read_uploaded_table(uploaded_file)
    except Exception as exc:
        return {
            "product_name": product_name,
            "source_file": source_file,
            "ingredients": [],
            "preview": pd.DataFrame(),
            "error": f"파일 읽기 실패: {type(exc).__name__}: {exc}",
        }

    if dataframe.empty or dataframe.shape[1] == 0:
        return {
            "product_name": product_name,
            "source_file": source_file,
            "ingredients": [],
            "preview": dataframe,
            "error": "읽을 수 있는 성분 행이 없습니다.",
        }

    ingredients = dedupe_preserve(
        dataframe.iloc[:, 0]
        .dropna()
        .map(clean_text)
        .tolist()
    )
    return {
        "product_name": product_name,
        "source_file": source_file,
        "ingredients": ingredients,
        "preview": dataframe.head(10),
        "error": None if ingredients else "유효한 성분이 없습니다.",
    }


# ============================================================
# API 호출
# ============================================================
def call_single_market(
    ingredients: Sequence[str],
    target: str,
) -> dict:
    response = requests.post(
        COMPLIANCE_API_URL,
        json={"ingredients": list(ingredients), "target": target},
        timeout=120,
    )
    if response.status_code != 200:
        try:
            detail = response.json().get("detail", response.text)
        except ValueError:
            detail = response.text
        raise RuntimeError(f"API {response.status_code}: {detail}")
    payload = response.json()
    if not isinstance(payload, dict):
        raise RuntimeError("API 응답 구조가 올바르지 않습니다.")
    return payload


def analyze_product(
    ingredients: Sequence[str],
    targets: Sequence[str],
) -> Tuple[Dict[str, dict], Dict[str, str]]:
    try:
        response = requests.post(
            MULTI_COMPLIANCE_API_URL,
            json={
                "ingredients": list(ingredients),
                "targets": list(targets),
            },
            timeout=max(120, 45 * len(targets)),
        )
        if response.status_code == 200:
            payload = response.json()
            results = payload.get("results") or {}
            failures = payload.get("failed_targets") or {}
            if isinstance(results, dict) and isinstance(failures, dict):
                return results, {
                    clean_text(key): clean_text(value)
                    for key, value in failures.items()
                }
        # v2가 아직 배포되지 않은 서버에서는 v1 반복 호출로 자동 대체한다.
        if response.status_code not in {404, 405, 422, 500, 502, 503, 504}:
            try:
                detail = response.json().get("detail", response.text)
            except ValueError:
                detail = response.text
            raise RuntimeError(f"다중시장 API {response.status_code}: {detail}")
    except requests.RequestException:
        pass

    results: Dict[str, dict] = {}
    failures: Dict[str, str] = {}
    for target in targets:
        try:
            results[target] = call_single_market(ingredients, target)
        except Exception as exc:
            failures[target] = f"{type(exc).__name__}: {exc}"
    return results, failures


# ============================================================
# 결과 표시 도우미
# ============================================================
def render_market_summary(target: str, result_data: dict) -> None:
    counts = status_counts(result_data)
    decision = market_decision(result_data)
    st.markdown(f"#### {MARKET_LABELS.get(target, target)}")
    cols = st.columns(7)
    labels = [
        ("통과", counts["PASS"]),
        ("금지", counts["BANNED"]),
        ("제한", counts["RESTRICTED"]),
        ("표시", counts["WARNING_REQUIRED"]),
        ("규제 대상", counts["REGULATED"]),
        ("수동 검토", counts["REVIEW_REQUIRED"]),
        ("명칭 검증", counts["VERIFICATION_REQUIRED"]),
    ]
    for column, (label, value) in zip(cols, labels):
        column.metric(label, value)

    status = dominant_status(result_data)
    message = f"{decision['overall']} — {decision['possibility']}"
    if status == "BANNED":
        st.error(message)
    elif status == "PASS":
        st.success(message)
    else:
        st.warning(message)

    rows = []
    for detail in result_data.get("report_details") or []:
        raw_status = normalize_status(
            detail.get("compliance_status")
            or detail.get("restriction_type")
        )
        rows.append(
            {
                "성분명": clean_text(detail.get("original_ingredient")),
                "INCI": clean_text(detail.get("inci_name")),
                "CAS": clean_text(detail.get("cas_number"), "N/A"),
                "판정": STATUS_LABELS.get(raw_status, raw_status),
                "근거·확인사항": normalized_reason(detail, target),
                "분석결과에 따른 조치": action_for_detail(detail, target),
            }
        )
    st.dataframe(
        pd.DataFrame(rows),
        hide_index=True,
        use_container_width=True,
    )


def render_halal_summary(result_data: dict) -> None:
    counts = status_counts(result_data)
    decision = halal_decision(result_data)
    st.markdown("#### HALAL 추가 성분 검토")
    cols = st.columns(4)
    cols[0].metric("위험 후보 미확인", counts["PASS"])
    cols[1].metric("할랄 금지", counts["BANNED"])
    cols[2].metric(
        "공식 기준 검토",
        counts["REVIEW_REQUIRED"] + counts["REGULATED"],
    )
    cols[3].metric("기원·구성·인증 확인", counts["VERIFICATION_REQUIRED"])
    if counts["BANNED"]:
        st.error(f"{decision['overall']} — {decision['possibility']}")
    elif sum(value for key, value in counts.items() if key != "PASS"):
        st.warning(f"{decision['overall']} — {decision['possibility']}")
    else:
        st.success(f"{decision['overall']} — {decision['possibility']}")

    rows = []
    for detail in result_data.get("report_details") or []:
        raw_status = normalize_status(
            detail.get("compliance_status")
            or detail.get("restriction_type")
        )
        rows.append(
            {
                "성분명": clean_text(detail.get("original_ingredient")),
                "INCI": clean_text(detail.get("inci_name")),
                "검토 상태": (
                    "할랄 위험 후보 미확인"
                    if raw_status == "PASS"
                    else clean_text(
                        detail.get("verification_type"),
                        STATUS_BADGES.get(raw_status, raw_status),
                    )
                ),
                "필요한 자료": required_evidence_for_detail(
                    detail,
                    raw_status,
                    "HALAL",
                ),
                "분석결과에 따른 조치": action_for_detail(detail, "HALAL"),
            }
        )
    st.dataframe(
        pd.DataFrame(rows),
        hide_index=True,
        use_container_width=True,
    )


# ============================================================
# 언어별 다운로드 파일 생성
# ============================================================
def build_language_outputs(
    analysis_result: dict,
    language_code: str,
) -> dict:
    if language_code not in OUTPUT_LANGUAGES:
        raise ValueError(f"지원하지 않는 출력 언어입니다: {language_code}")
    translator = report_translator if client is not None else None
    localized_products: List[dict] = []
    selected_markets = analysis_result.get("selected_markets") or []

    for product in analysis_result.get("products") or []:
        excel_data = create_product_excel_bytes(
            product_name=product["product_name"],
            source_file=product["source_file"],
            market_results_map=product["market_results"],
            selected_markets=selected_markets,
            halal_result=product.get("halal_result"),
            language_code=language_code,
            translator=translator,
        )
        report_data = create_product_report_bytes(
            product_name=product["product_name"],
            source_file=product["source_file"],
            market_results_map=product["market_results"],
            selected_markets=selected_markets,
            halal_result=product.get("halal_result"),
            language_code=language_code,
            translator=translator,
        )
        localized_products.append(
            {
                **product,
                "excel_data": excel_data,
                "report_data": report_data,
            }
        )

    bundle_data = create_bundle_zip_bytes(
        localized_products,
        analysis_result.get("failures") or [],
        language_code=language_code,
    )
    return {
        "language_code": language_code,
        "products": localized_products,
        "bundle_data": bundle_data,
    }


def build_delivery_outputs(
    analysis_result: dict,
    additional_language_code: Optional[str],
) -> dict:
    """Always generate English and optionally one additional language."""
    language_codes = ["en"]
    if (
        additional_language_code
        and additional_language_code != "none"
        and additional_language_code != "en"
    ):
        if additional_language_code not in OUTPUT_LANGUAGES:
            raise ValueError(
                f"지원하지 않는 추가 언어입니다: {additional_language_code}"
            )
        language_codes.append(additional_language_code)

    outputs = {
        code: build_language_outputs(analysis_result, code)
        for code in language_codes
    }

    combined = io.BytesIO()
    with zipfile.ZipFile(
        combined,
        "w",
        compression=zipfile.ZIP_DEFLATED,
    ) as archive:
        for code, output in outputs.items():
            folder = LANGUAGE_FILE_SUFFIXES[code]
            with zipfile.ZipFile(
                io.BytesIO(output["bundle_data"]),
                "r",
            ) as source_zip:
                for member in source_zip.infolist():
                    if member.is_dir():
                        continue
                    archive.writestr(
                        f"{folder}/{member.filename}",
                        source_zip.read(member),
                    )

    suffixes = "+".join(
        LANGUAGE_FILE_SUFFIXES[code] for code in language_codes
    )
    return {
        "language_codes": language_codes,
        "outputs": outputs,
        "bundle_data": combined.getvalue(),
        "bundle_name": (
            f"Multi_Product_Regulatory_Screening_Results_{suffixes}.zip"
        ),
    }


# ============================================================
# 앱 실행
# ============================================================
def run_app() -> None:
    initialize_session_state()

    # --------------------------------------------------------
    # 사이드바
    # --------------------------------------------------------
    st.sidebar.success(f"SYSTEM ONLINE · {APP_VERSION}")
    st.sidebar.caption(f"Report engine · {REPORT_BUILD_ID}")
    if client is not None:
        st.sidebar.caption("다국어 출력 준비됨")
    else:
        st.sidebar.warning("다국어 출력 비활성 — OPENAI_API_KEY 확인 필요")

    database_status = fetch_database_status()
    if database_status:
        total_confirmed = sum(
            safe_int(
                item.get("confirmed_records")
                or item.get("loaded_records")
            )
            for item in database_status.values()
            if isinstance(item, dict)
        )
        total_review = sum(
            safe_int(item.get("review_rows"))
            for item in database_status.values()
            if isinstance(item, dict)
        )
        st.sidebar.caption(
            f"확정 DB {total_confirmed:,}건 · 검토대기 {total_review:,}건"
        )
    else:
        st.sidebar.caption("데이터베이스 상태 조회 불가")

    st.sidebar.markdown("---")
    st.sidebar.subheader("라이선스")
    entered_key = st.sidebar.text_input(
        "License Key",
        type="password",
    )

    auth_tier = "FREE"
    current_uses = 0
    if entered_key:
        if st.session_state.last_entered_key != entered_key:
            tier, message, uses = check_license_status(entered_key)
            st.session_state.current_auth_tier = tier
            st.session_state.current_auth_msg = message
            st.session_state.last_entered_key = entered_key
            st.session_state.standard_uses = uses
        auth_tier = st.session_state.current_auth_tier
        current_uses = safe_int(st.session_state.get("standard_uses"))
        message = st.session_state.current_auth_msg
        if auth_tier in {"PRO", "STANDARD"}:
            st.sidebar.success(message)
        elif auth_tier == "ERROR":
            st.sidebar.warning(message)
        else:
            st.sidebar.error(message)
    else:
        st.sidebar.warning(
            "무료 이용: "
            f"잔여 {st.session_state.free_analysis_units_left}건"
        )

    is_pro = auth_tier == "PRO"
    is_standard = auth_tier == "STANDARD"
    is_free = not entered_key

    # --------------------------------------------------------
    # 메인
    # --------------------------------------------------------
    st.title("Global K-Beauty Compliance")
    st.markdown(
        "##### 제품별 다중시장 성분 규제 분석과 HALAL 추가검토"
    )

    st.info(
        "7개 국가·권역 규제시장을 복수 선택하고, HALAL은 별도 추가검토로 선택합니다. "
        "업로드한 제품은 서로 합치지 않고 제품별로 분석하며 Excel과 Word 보고서를 각각 생성합니다."
    )

    if not st.session_state.disclaimer_agreed:
        st.markdown("### 필수 고지")
        st.warning(
            "이 서비스는 규제 사전 스크리닝 도구이며 법률 자문, 제품 등록 승인, "
            "통관 허가 또는 할랄 인증서를 대신하지 않습니다."
        )
        if st.checkbox("위 고지를 읽고 동의합니다."):
            st.session_state.disclaimer_agreed = True
            st.rerun()
        st.stop()

    if st.button("고지 다시 확인"):
        st.session_state.disclaimer_agreed = False
        reset_results()
        st.rerun()

    st.markdown("---")
    st.subheader("1. 분석 범위 선택")

    selected_markets = st.multiselect(
        "국가·권역 규제시장 선택",
        options=REGULATORY_MARKETS,
        format_func=lambda code: MARKET_OPTIONS[code],
        default=["EU", "US", "CN"],
        on_change=reset_results,
    )

    halal_selected = st.checkbox(
        "HALAL 추가검토",
        value=False,
        help=(
            "원료 기원, 동물 유래 가능성, 알코올 관련 성분, "
            "복합원료 구성, 제조공정 및 인증자료 확인 대상을 추가로 선별합니다."
        ),
        on_change=reset_results,
    )

    if not selected_markets:
        st.warning("국가·권역 규제시장을 1개 이상 선택하십시오.")

    st.subheader("2. 제품 파일 업로드")
    upload_types = ["csv", "xlsx", "xls", "jpg", "jpeg", "png"]
    multiple_allowed = is_pro or is_free
    uploaded_files = st.file_uploader(
        (
            "제품별 전성분 파일 업로드 — 여러 파일 가능"
            if multiple_allowed
            else "제품 전성분 파일 1개 업로드"
        ),
        type=upload_types,
        accept_multiple_files=multiple_allowed,
        on_change=reset_results,
    )

    if uploaded_files is None:
        uploaded_list: List[Any] = []
    elif isinstance(uploaded_files, list):
        uploaded_list = uploaded_files
    else:
        uploaded_list = [uploaded_files]

    products: List[dict] = []
    if uploaded_list:
        for index, uploaded_file in enumerate(uploaded_list):
            product = extract_product(uploaded_file)
            with st.expander(
                f"{index + 1}. {product['source_file']}",
                expanded=True,
            ):
                if product.get("error"):
                    st.error(product["error"])
                edited_name = st.text_input(
                    "제품명",
                    value=product["product_name"],
                    key=f"product_name_{index}_{product['source_file']}",
                )
                product["product_name"] = clean_text(
                    edited_name,
                    product["product_name"],
                )
                if not product["preview"].empty:
                    st.dataframe(
                        product["preview"],
                        hide_index=True,
                        use_container_width=True,
                    )
                st.caption(
                    f"분석 성분 수: {len(product['ingredients']):,}개"
                )
            if product["ingredients"] and not product.get("error"):
                products.append(product)

    targets = list(selected_markets)
    if halal_selected:
        targets.append("HALAL")

    analysis_units = len(products) * len(targets)
    st.subheader("3. 분석 실행")
    metric_cols = st.columns(4)
    metric_cols[0].metric("제품 수", len(products))
    metric_cols[1].metric("규제시장 수", len(selected_markets))
    metric_cols[2].metric("HALAL", "추가" if halal_selected else "미선택")
    metric_cols[3].metric("예상 분석 건수", analysis_units)

    if is_standard and len(products) > 1:
        st.error("Standard는 제품 파일 1개만 분석할 수 있습니다.")

    if is_standard and current_uses + analysis_units > 50:
        st.error(
            f"현재 잔여 분석 한도로 {analysis_units}건을 실행할 수 없습니다."
        )

    if is_free and analysis_units > st.session_state.free_analysis_units_left:
        st.error(
            "무료 잔여 분석 건수보다 요청한 분석 건수가 많습니다. "
            "제품 또는 시장 수를 줄이십시오."
        )

    can_run = (
        bool(products)
        and bool(selected_markets)
        and not (is_standard and len(products) > 1)
        and not (is_standard and current_uses + analysis_units > 50)
        and not (
            is_free
            and analysis_units > st.session_state.free_analysis_units_left
        )
        and auth_tier not in {"INVALID", "EXPIRED", "ERROR"}
    )
    if is_free:
        can_run = (
            bool(products)
            and bool(selected_markets)
            and analysis_units <= st.session_state.free_analysis_units_left
        )

    run_clicked = st.button(
        "다중제품·다중시장 분석 실행",
        type="primary",
        use_container_width=True,
        disabled=not can_run,
    )

    if run_clicked:
        progress = st.progress(0)
        status_box = st.empty()
        product_outputs: List[dict] = []
        failures: List[dict] = []
        completed_units = 0

        for product_index, product in enumerate(products, start=1):
            status_box.info(
                f"{product_index}/{len(products)} — "
                f"{product['product_name']} 분석 중"
            )
            try:
                result_map, target_failures = analyze_product(
                    product["ingredients"],
                    targets,
                )
            except Exception as exc:
                result_map = {}
                target_failures = {
                    target: f"{type(exc).__name__}: {exc}"
                    for target in targets
                }

            for target, error in target_failures.items():
                failures.append(
                    {
                        "product_name": product["product_name"],
                        "target": target,
                        "error": error,
                    }
                )

            market_results_map = {
                target: result_map[target]
                for target in selected_markets
                if target in result_map
            }
            halal_result = result_map.get("HALAL") if halal_selected else None
            completed_units += len(market_results_map) + (
                1 if halal_result is not None else 0
            )

            if market_results_map:
                product_outputs.append(
                    {
                        "product_name": product["product_name"],
                        "source_file": product["source_file"],
                        "ingredients": product["ingredients"],
                        "market_results": market_results_map,
                        "halal_result": halal_result,
                    }
                )

            progress.progress(product_index / len(products))

        if is_standard and completed_units:
            success, message = consume_standard_units(
                entered_key,
                completed_units,
            )
            if not success:
                st.warning(message)
        elif is_free:
            st.session_state.free_analysis_units_left = max(
                0,
                st.session_state.free_analysis_units_left - completed_units,
            )

        st.session_state.localized_outputs = {}
        st.session_state.analysis_result = {
            "result_id": uuid.uuid4().hex,
            "products": product_outputs,
            "failures": failures,
            "requested_units": analysis_units,
            "completed_units": completed_units,
            "selected_markets": selected_markets,
            "halal_selected": halal_selected,
        }
        progress.progress(1.0)
        status_box.success(
            f"분석 완료 — 성공 {completed_units}/{analysis_units}건"
        )
        time.sleep(0.3)
        st.rerun()

    # --------------------------------------------------------
    # 결과
    # --------------------------------------------------------
    analysis_result = st.session_state.analysis_result
    if analysis_result:
        st.markdown("---")
        st.subheader("분석 결과 및 다운로드")
        cols = st.columns(4)
        cols[0].metric("결과 제품", len(analysis_result["products"]))
        cols[1].metric("요청 건수", analysis_result["requested_units"])
        cols[2].metric("성공 건수", analysis_result["completed_units"])
        cols[3].metric("실패 건수", len(analysis_result["failures"]))

        st.markdown("#### 출력 언어")
        st.info(
            "English Excel·Word는 기본으로 항상 포함됩니다. "
            "필요한 경우 추가 언어 1개를 선택할 수 있습니다."
        )
        additional_options = [
            "none",
            *[code for code in OUTPUT_LANGUAGES if code != "en"],
        ]
        additional_language_code = st.selectbox(
            "추가 출력 언어",
            options=additional_options,
            format_func=lambda code: (
                "추가 언어 없음 — English only"
                if code == "none"
                else OUTPUT_LANGUAGES[code]
            ),
            key=(
                f"additional_download_language_"
                f"{analysis_result['result_id']}"
            ),
        )
        st.caption(
            "언어 선택은 분석을 다시 실행하거나 분석 건수를 추가 차감하지 "
            "않습니다. INCI, CAS 번호, 공식 기관 약어, URL과 원문 식별자는 "
            "번역하지 않습니다."
        )
        output_cache_key = (
            f"{analysis_result['result_id']}::{REPORT_BUILD_ID}::en::"
            f"{additional_language_code}"
        )
        delivery_output = st.session_state.localized_outputs.get(
            output_cache_key
        )
        additional_label = (
            ""
            if additional_language_code == "none"
            else f" + {OUTPUT_LANGUAGES[additional_language_code]}"
        )
        translation_ready = client is not None
        if not translation_ready:
            st.error(
                "영문 및 다국어 파일 생성 기능을 사용할 수 없습니다. "
                "관리자가 OPENAI_API_KEY 설정을 확인해야 합니다."
            )
        if st.button(
            f"English{additional_label} Excel·Word 파일 생성",
            type="primary",
            use_container_width=True,
            disabled=not translation_ready,
            key=f"generate_{output_cache_key}",
        ):
            try:
                with st.spinner(
                    f"English{additional_label} 출력 파일 생성 중..."
                ):
                    delivery_output = build_delivery_outputs(
                        analysis_result,
                        additional_language_code,
                    )
                    st.session_state.localized_outputs[
                        output_cache_key
                    ] = delivery_output
                st.success(
                    "영문 기본본과 선택한 추가 언어본 생성이 완료되었습니다."
                )
            except Exception as exc:
                st.error(
                    f"출력 파일 생성 실패: {type(exc).__name__}: {exc}"
                )
                delivery_output = None

        if delivery_output:
            st.download_button(
                "전체 Excel·Word 결과 ZIP 다운로드",
                data=delivery_output["bundle_data"],
                file_name=delivery_output["bundle_name"],
                mime="application/zip",
                use_container_width=True,
                key=f"bundle_{output_cache_key}",
            )
        else:
            st.info(
                "English 기본본과 필요한 추가 언어를 선택한 뒤 "
                "파일 생성 버튼을 누르십시오."
            )

        if analysis_result["failures"]:
            st.error("일부 제품·시장 분석이 실패했습니다.")
            st.dataframe(
                pd.DataFrame(analysis_result["failures"]),
                hide_index=True,
                use_container_width=True,
            )

        for product_index, product in enumerate(
            analysis_result["products"],
            start=1,
        ):
            st.markdown("---")
            st.markdown(
                f"### {product_index}. {product['product_name']}"
            )
            if delivery_output:
                for output_language_code in delivery_output[
                    "language_codes"
                ]:
                    localized_output = delivery_output["outputs"][
                        output_language_code
                    ]
                    localized_product = localized_output["products"][
                        product_index - 1
                    ]
                    with st.expander(
                        f"{OUTPUT_LANGUAGES[output_language_code]} 다운로드",
                        expanded=(output_language_code == "en"),
                    ):
                        download_cols = st.columns(2)
                        with download_cols[0]:
                            st.download_button(
                                "Excel 규제분석결과 다운로드",
                                data=localized_product["excel_data"],
                                file_name=output_file_name(
                                    product["product_name"],
                                    "excel",
                                    output_language_code,
                                    "xlsx",
                                ),
                                mime=(
                                    "application/vnd.openxmlformats-officedocument."
                                    "spreadsheetml.sheet"
                                ),
                                use_container_width=True,
                                key=(
                                    f"excel_{output_cache_key}_"
                                    f"{output_language_code}_{product_index}"
                                ),
                            )
                        with download_cols[1]:
                            st.download_button(
                                "Word 규제스크리닝 보고서 다운로드",
                                data=localized_product["report_data"],
                                file_name=output_file_name(
                                    product["product_name"],
                                    "report",
                                    output_language_code,
                                    "docx",
                                ),
                                mime=(
                                    "application/vnd.openxmlformats-officedocument."
                                    "wordprocessingml.document"
                                ),
                                use_container_width=True,
                                key=(
                                    f"docx_{output_cache_key}_"
                                    f"{output_language_code}_{product_index}"
                                ),
                            )

            tabs = st.tabs(
                [
                    MARKET_LABELS.get(target, target)
                    for target in product["market_results"]
                ]
                + (["HALAL 추가검토"] if product["halal_result"] else [])
            )
            tab_index = 0
            for target, result_data in product["market_results"].items():
                with tabs[tab_index]:
                    render_market_summary(target, result_data)
                    if product["halal_result"]:
                        st.info(
                            "이 시장의 보고서 장에는 HALAL 독립 분석 결과가 "
                            "현지 인증·바이어·유통채널 요구에 미치는 영향도 함께 표시됩니다."
                        )
                tab_index += 1
            if product["halal_result"]:
                with tabs[tab_index]:
                    render_halal_summary(product["halal_result"])


if __name__ == "__main__":
    run_app()
